[env:esp32dev]
platform = espressif32
board = esp32dev ; Ou um modelo mais específico do seu ESP32 DevKit V4 se souber
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient @ ^2.8         ; Para MQTT
    bogde/HX711 @ ^0.7.5                  ; Para o sensor de peso HX711
    adafruit/DHT sensor library @ ^1.4.6  ; Para o sensor DHT
    adafruit/Adafruit Unified Sensor @ ^1.1.14 ; Dependência da biblioteca DHT

; Adicione esta linha se quiser especificar a porta de upload (opcional)
; upload_port = COM_OU_TTY_AQUI 
; Adicione esta linha se quiser especificar a porta do monitor serial (opcional)
; monitor_port = COM_OU_TTY_AQUI